## Trigger Kustomize file (overlay): [timer] : timer/kustomization.yaml
# See Kustomize reference for guides and examples
# https://kubectl.docs.kubernetes.io/references/kustomize/

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
configMapGenerator:
  - name: environment-properties
    envs:
      - environment-properties.env
    behavior: merge
secretGenerator:
  - name: secure-properties
    envs:
      - secure-properties.env
    type: Opaque
    behavior: merge
