apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret-example
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: jerhs-secret
    creationPolicy: 'Owner'
    deletionPolicy: "Delete"
  data:
  - secretKey: apikey
    remoteRef:
      key: generic/project/otc-setup/jerhs-pws
      property: apikey
