apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: endpoint-listener
spec:
  triggers:
    - name: simple-endpoint-test
      bindings:
        - ref: pse-test-pipeline-binding
      template:
        ref: pse-test-pipeline-template
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: pse-test-pipeline-binding
spec:
  params:
  - name: public-endpoint
    value: "public-endpoint-address"
  - name: private-endpoint
    value: "private-endpoint-address"
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: pse-test-pipeline-template
spec:
  params:
    - name: private-endpoint
      description: Public Endpoint
      default: https://private-worker-service.eu-gb.devops.cloud.ibm.com
    - name: private-endpoint
      description: Private Endpoint
      default: https://private-worker-service.private.eu-gb.devops.cloud.ibm.com
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: pse-test-pipeline-run-
      spec:
        pipelineRef:
          name: pse-test-pipeline
        params:
          - name: public-endpoint
            value: $(tt.params.public-endpoint)
          - name: private-endpoint
            value: $(tt.params.private-endpoint)
