apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: big-echo-pipeline
spec:
  params:
  tasks:
    - name: show-build-number
      taskRef:
        name: simple-task
    - name: big-echo-task
      taskRef:
        name: big-echo-task
