apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pse-test-pipeline
spec:
  params:
    - name: public-endpoint
      description: Publicly available endpoint
      default: https://private-worker-service.eu-gb.devops.cloud.ibm.com
    - name: private-endpoint
      description: Privately accessible only endpoint
      default: https://private-worker-service.private.eu-gb.devops.cloud.ibm.com 
  tasks:
    - name: test-endpoints
      taskRef:
        name: endpoint-task
      params:
        - name: public-endpoint
          value: $(params.public-endpoint)
        - name: private-endpoint
          value: $(params.private-endpoint)
    - name: test-bluefringe
      taskRef:
        name: testing-bluefringe
    - name: testing-connectivity
      taskRef:
        name: testing-dns       
