apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: endpoint-task
spec:
  steps:
    - name: test-public-endpoint
      image: ubuntu
      imagePullPolicy: IfNotPresent
      envFrom:
        - configMapRef:
            name: environment-properties
        - secretRef:
            name: secure-properties     
      command: ["/bin/bash", "-c"]
      args:
        - echo -e "Testing \033[36mPUBLIC\033[0m endpoint";
          env;
          curl ${public-endpoint};
      steps:
    - name: test-private-endpoint
      image: ubuntu
      imagePullPolicy: IfNotPresent
      envFrom:
        - configMapRef:
            name: environment-properties
        - secretRef:
            name: secure-properties     
      command: ["/bin/bash", "-c"]
      args:
        - echo -e "Testing \033[36mPRIVATE\033[0m endpoint";
          env;
          curl ${private-endpoint};
